name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test-and-Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20] # Node.js 18ê³¼ 20ì—ì„œ ì‹¤í–‰
    steps:
      # ê¸°ë³¸ ì •ë³´ ì¶œë ¥
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      # ë ˆí¬ì§€í† ë¦¬ ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      # Node.js ì„¤ì •
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # ì˜ì¡´ì„± ì„¤ì¹˜
      - name: Install dependencies
        run: npm install

      # í…ŒìŠ¤íŠ¸ ì‹¤í–‰
      - name: Run tests
        run: npm run test

      # ë¹Œë“œ ì‹¤í–‰
      - name: Run build
        run: npm run build

      # ê¸°ë³¸ íŒŒì¼ ë¦¬ìŠ¤íŠ¸ ì¶œë ¥
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # ìƒíƒœ í™•ì¸
      - run: echo "ğŸ This job's status is ${{ job.status }}."
